export const CARRINHO_ACTIONS = {
  ADD_CARRINHO: "ADD_CARRINHO",
  REMOVE_CARRINHO: "REMOVE_CARRINHO",
  ADICIONA_QUANTIDADE: "ADICIONA_QUANTIDADE",
  REMOVE_QUANTIDADE: "REMOVE_QUANTIDADE",
  LIMPAR_CARRINHO: "LIMPAR_CARRINHO",
};
